-- ==========================================================================
-- ⛔ 本文件已废弃（2026-09-01），请勿在 Supabase SQL Editor 中执行！
-- ==========================================================================
-- 废弃原因：
--   本文件中的 create_department（4 参）/ update_department（5 参）/
--   delete_department 是部门 RPC 的最早版本。后续 department-tree.sql
--   和 department-entity-permissions.sql 已将其升级为 6 参 / 7 参新版
--   （支持组织树 parent_id/dept_type + 两级权限）。
--
--   ⚠️ 如果重跑本文件，CREATE OR REPLACE 会按旧签名重新创建函数，
--   与新版并存形成多个重载 → PostgREST 报
--   PGRST203 could not choose best candidate → 界面建部门/改部门全坏。
--   2026-09-01 服务器库的 PGRST203 故障即由此导致。
--
--   部门 RPC 的唯一权威维护文件：
--     sql/department-fix-v1.sql（2026-09-01 起，含全部重载清理 + 最新实现）
--   历史演进文件（勿单独重跑函数定义部分）：
--     sql/department-tree.sql
--     sql/department-entity-permissions.sql
--
-- 本文件保留原文仅作历史参考，所有函数定义已移除（见 git 历史）。
-- 需要的列级变更（needs_report / can_view_admin）已由后续文件覆盖：
--   ALTER TABLE ... ADD COLUMN IF NOT EXISTS 在 department-tree.sql 中亦有体现，
--   全新环境请按 docs 部署文档顺序执行整条 SQL 链即可。
-- ==========================================================================

-- 部门管理功能现状（由 department-fix-v1.sql 提供）：
--   create_department(TEXT, INTEGER, BOOLEAN, BOOLEAN, UUID, TEXT)
--     公司级管理员：任意类型/任意上级；经营实体：仅本部门下项目部
--   update_department(UUID, TEXT, INTEGER, BOOLEAN, BOOLEAN, UUID, TEXT)
--     公司级全量；经营实体仅限本部门下的项目部
--   delete_department(UUID)
--     公司级全量（公司根/有下级除外）；经营实体仅限本部门下的项目部
